// Mock data for testing

export const mockSession = {
  id: 'test-session-123',
  current_step: 'selection',
  hobbies_json: JSON.stringify(['Photography', 'Hiking', 'Cooking']),
  created_at: new Date().toISOString(),
};

export const mockConcepts = [
  {
    id: 'concept-1',
    title: 'Camera Hiker Chef',
    image_url: 'https://example.com/concept1.png',
    type: 'Literal',
    prompt: 'A gray clay sculpture combining a camera, hiking boots, and chef hat',
  },
  {
    id: 'concept-2',
    title: 'Mountain Kitchen',
    image_url: 'https://example.com/concept2.png',
    type: 'Literal',
    prompt: 'A gray clay sculpture of a mountain with a kitchen on top',
  },
  {
    id: 'concept-3',
    title: 'Abstract Explorer',
    image_url: 'https://example.com/concept3.png',
    type: 'Artistic',
    prompt: 'An abstract gray sculpture representing adventure and creativity',
  },
  {
    id: 'concept-4',
    title: 'Culinary Journey',
    image_url: 'https://example.com/concept4.png',
    type: 'Artistic',
    prompt: 'A stylized gray sculpture of a winding path with food elements',
  },
];

export const mockAsset = {
  id: 1,
  session_id: 'test-session-123',
  image_url: 'https://example.com/concept1.png',
  status: 'generated',
  stl_r2_path: null,
  created_at: new Date().toISOString(),
};

export const mockAssetProcessing = {
  ...mockAsset,
  status: 'processing',
};

export const mockAssetCompleted = {
  ...mockAsset,
  status: 'completed',
  stl_r2_path: 'models___test-session-123___concept-1.stl',
};

export const mockSlicerResult = {
  material_grams: 64.21,
  print_duration_minutes: 245,
  gcode_r2_path: 'gcode___test-session-123___concept-1.gcode',
  stats: {
    object_material_g: 58.5,
    support_material_g: 5.71,
    total_material_g: 64.21,
    print_time_minutes: 245,
    layer_count: 400,
  },
};

export const mockPricing = {
  material_cost: 1.93,
  service_fee: 12.0,
  shipping: 9.0,
  total: 22.93,
};

export const mockOrder = {
  id: 'order-123',
  session_id: 'test-session-123',
  user_email: 'test@example.com',
  status: 'pending',
  price_cents: 2293,
  material_grams: 64.21,
  print_duration_minutes: 245,
  gcode_r2_path: 'gcode___test-session-123___concept-1.gcode',
  final_stl_r2_path: 'models___test-session-123___concept-1.stl',
  created_at: new Date().toISOString(),
};

// Mock STL data (minimal valid STL)
export const mockSTLContent = `solid test
facet normal 0 0 1
  outer loop
    vertex 0 0 0
    vertex 1 0 0
    vertex 0 1 0
  endloop
endfacet
endsolid test`;

// Mock G-code data
export const mockGCodeContent = `; generated by PrusaSlicer
; filament_density = 1.24
M104 S210 ; set extruder temp
M140 S60 ; set bed temp
G28 ; home all axes
G1 X10 Y10 Z0.2 E1.0 ; extrusion move
G1 X20 Y20 E2.0
G1 X30 Y30 E3.0
M104 S0 ; turn off extruder
M140 S0 ; turn off bed`;

// Mock API responses
export const mockAPIResponses = {
  health: { status: 'ok' },
  
  generate: {
    session_id: 'test-session-123',
    concepts: mockConcepts,
  },
  
  sessionStatus: {
    session_id: 'test-session-123',
    current_step: 'studio',
    selected_concept_id: 'concept-1',
    assets: [mockAssetCompleted],
  },
  
  slice: {
    success: true,
    ...mockSlicerResult,
  },
};

// Mock Cloudflare AI responses
export const mockLlamaResponse = {
  response: JSON.stringify({
    concepts: mockConcepts.map(c => ({
      title: c.title,
      prompt: c.prompt,
      type: c.type,
    })),
  }),
};

export const mockFluxResponse = {
  image: new Uint8Array([137, 80, 78, 71]), // PNG header
};
